#!/bin/sh

value=`cat '/sys/class/leds/asus::screenpad/brightness'`
current=$(((value +1) / 32 + 1))
if [ $value = 1 ]; then
    current=0
fi

choice=$1

case "$1" in
up)
   choice=$((current + 1))
;;
down)
   choice=$((current - 1))
;;
esac

case "$choice" in
0) echo 1 > '/sys/class/leds/asus::screenpad/brightness' ;;
1) echo 4 > '/sys/class/leds/asus::screenpad/brightness' ;;
2) echo 31 > '/sys/class/leds/asus::screenpad/brightness' ;;
3) echo 63 > '/sys/class/leds/asus::screenpad/brightness' ;;
4) echo 95 > '/sys/class/leds/asus::screenpad/brightness' ;;
5) echo 127 > '/sys/class/leds/asus::screenpad/brightness' ;;
6) echo 159 > '/sys/class/leds/asus::screenpad/brightness' ;;
7) echo 191 > '/sys/class/leds/asus::screenpad/brightness' ;;
8) echo 223 > '/sys/class/leds/asus::screenpad/brightness' ;;
9) echo 255 > '/sys/class/leds/asus::screenpad/brightness' ;;
off) echo 0 > '/sys/class/leds/asus::screenpad/brightness' ;;
toggle)
   if [ $value = 0 ] ; then
     echo 255 > '/sys/class/leds/asus::screenpad/brightness'
   else
     echo 0 > '/sys/class/leds/asus::screenpad/brightness'
   fi
;;
*)
   echo 'Usage:'
   echo '  screenpad off     Turn ScreenPad off'
   echo '  screenpad N       Turn ScreenPad on and set brightness (N = 0...9)'
   echo '  screenpad toggle  Toggle between off and 9'
   echo '  screenpad up      Increase brightness'
   echo '  screenpad down    Decrease brightness'
;;
esac
